-- Phase 4 — PostGIS geometry + objectid (Q7 = native geometry)
-- Requires PostgreSQL 14+ for EXECUTE FUNCTION in triggers; use EXECUTE PROCEDURE on PG 13.

ALTER TABLE ecd_center ADD COLUMN IF NOT EXISTS geom geometry(Point, 4326);
UPDATE ecd_center SET geom = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
  WHERE latitude IS NOT NULL AND longitude IS NOT NULL AND geom IS NULL;
CREATE INDEX IF NOT EXISTS idx_ecd_center_geom ON ecd_center USING GIST (geom);

ALTER TABLE administrative_unit ADD COLUMN IF NOT EXISTS geom geometry(Point, 4326);
UPDATE administrative_unit SET geom = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
  WHERE latitude IS NOT NULL AND longitude IS NOT NULL AND geom IS NULL;
CREATE INDEX IF NOT EXISTS idx_administrative_unit_geom ON administrative_unit USING GIST (geom);

CREATE OR REPLACE FUNCTION sync_point_geom() RETURNS trigger AS $$
BEGIN
  IF NEW.latitude IS NOT NULL AND NEW.longitude IS NOT NULL THEN
    NEW.geom := ST_SetSRID(ST_MakePoint(NEW.longitude, NEW.latitude), 4326);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ecd_center_geom ON ecd_center;
CREATE TRIGGER trg_ecd_center_geom BEFORE INSERT OR UPDATE OF latitude, longitude
  ON ecd_center FOR EACH ROW EXECUTE FUNCTION sync_point_geom();

DROP TRIGGER IF EXISTS trg_administrative_unit_geom ON administrative_unit;
CREATE TRIGGER trg_administrative_unit_geom BEFORE INSERT OR UPDATE OF latitude, longitude
  ON administrative_unit FOR EACH ROW EXECUTE FUNCTION sync_point_geom();

ALTER TABLE ecd_center ADD COLUMN IF NOT EXISTS objectid integer GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE administrative_unit ADD COLUMN IF NOT EXISTS objectid integer GENERATED BY DEFAULT AS IDENTITY;
