-- EGDB: add scenario_c columns missing on sde tables (no PostGIS — geom omitted).

ALTER TABLE sde.ecd_center
  ADD COLUMN IF NOT EXISTS objectid integer GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS status_id uuid,
  ADD COLUMN IF NOT EXISTS current_compliance_level_id uuid;

ALTER TABLE sde.administrative_unit
  ADD COLUMN IF NOT EXISTS objectid integer GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS level_id uuid;

CREATE UNIQUE INDEX IF NOT EXISTS ecd_center_objectid_key ON sde.ecd_center (objectid);
CREATE UNIQUE INDEX IF NOT EXISTS administrative_unit_objectid_key ON sde.administrative_unit (objectid);
CREATE INDEX IF NOT EXISTS ecd_center_status_id_idx ON sde.ecd_center (status_id);
CREATE INDEX IF NOT EXISTS ecd_center_current_compliance_level_id_idx
  ON sde.ecd_center (current_compliance_level_id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'sde' AND table_name = 'lookup_ecd_center_status'
  ) THEN
    UPDATE sde.ecd_center e
    SET status_id = l.id
    FROM sde.lookup_ecd_center_status l
    WHERE l.code = e.status::text AND e.status_id IS NULL;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'sde' AND table_name = 'lookup_compliance_classification'
  ) THEN
    UPDATE sde.ecd_center e
    SET current_compliance_level_id = l.id
    FROM sde.lookup_compliance_classification l
    WHERE l.code = e.current_compliance_level::text AND e.current_compliance_level_id IS NULL;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'sde' AND table_name = 'lookup_administrative_level'
  ) THEN
    UPDATE sde.administrative_unit u
    SET level_id = l.id
    FROM sde.lookup_administrative_level l
    WHERE l.code = u.level::text AND u.level_id IS NULL;
  END IF;
END $$;
